"""init database

Revision ID: 4a315a1b279a
Revises: 
Create Date: 2024-11-06 18:36:11.424104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a315a1b279a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trash',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_collected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trash_id'), 'trash', ['id'], unique=False)
    op.create_index(op.f('ix_trash_label'), 'trash', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trash_label'), table_name='trash')
    op.drop_index(op.f('ix_trash_id'), table_name='trash')
    op.drop_table('trash')
    # ### end Alembic commands ###
