"""update trash full notification

Revision ID: 8944f6a0b7ba
Revises: 4a315a1b279a
Create Date: 2024-11-15 10:34:35.154854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8944f6a0b7ba'
down_revision: Union[str, None] = '4a315a1b279a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trash_full_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trash_full_notifications_id'), 'trash_full_notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trash_full_notifications_id'), table_name='trash_full_notifications')
    op.drop_table('trash_full_notifications')
    # ### end Alembic commands ###
