"""add field is_full

Revision ID: b2409c7c2e55
Revises: 8944f6a0b7ba
Create Date: 2024-11-15 11:33:19.606867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2409c7c2e55'
down_revision: Union[str, None] = '8944f6a0b7ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trash_full_notifications', sa.Column('is_full', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trash_full_notifications', 'is_full')
    # ### end Alembic commands ###
