"""added is_collected column

Revision ID: cb3103117fc3
Revises: 0a1ab05ca1ce
Create Date: 2024-11-01 11:21:14.097819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3103117fc3'
down_revision: Union[str, None] = '0a1ab05ca1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trash', sa.Column('is_collected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trash', 'is_collected')
    # ### end Alembic commands ###
